# http://docs.travis-ci.com/user/customizing-the-build/
language: node_js
node_js:
  - 0.10
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - npm install -g bower
  - npm install -g chrome firefox karma@canary phantomjs karma-phantomjs-launcher karma-firefox-launcher jasmine-node@2.0.0
#  - npm install -g harp
  - npm install
  - bower install
script:
  - grunt test
  - jasmine-node --forceExit --coffee test/unit/crunchtaskSpec.coffee test/unit/declarationInstantiationSpec.coffee test/unit/apiSpec.coffee test/unit/apiChainabilitySpec.coffee test/unit/crunchtaskEventsSpec.coffee test/unit/convenienceForMethodSpec.coffee

