language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g bower
  - npm install -g chrome karma@canary phantomjs karma-phantomjs-launcher
#  - npm install -g harp
  - bower install
  - npm install
script: grunt test